lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-assemblyqc_logo_light.png
    - docs/images/nf-core-assemblyqc_logo_light.png
    - docs/images/nf-core-assemblyqc_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-assemblyqc_logo_light.png
    - docs/images/nf-core-assemblyqc_logo_light.png
    - docs/images/nf-core-assemblyqc_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - docs/README.md
    - .github/CONTRIBUTING.md
    - .github/workflows/linting.yml
    - LICENSE
  nextflow_config:
    - manifest.name
    - manifest.homePage
repository_type: pipeline
template:
  prefix: plant-food-research-open
  skip: []
