name: assembly-qc-pipeline-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - autopep8==2.0.1
      - Jinja2==3.1.2
      - MarkupSafe==2.1.1
      - numpy==1.24.1
      - pandas==1.5.2
      - pycodestyle==2.10.0
      - python-dateutil==2.8.2
      - pytz==2022.7
      - six==1.16.0
      - tabulate==0.9.0
      - tomli==2.0.1
