---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "custom_checkgff3fastacorrespondence"
description: "A custom bash script which checks the correspondence of a gff3 file with a fasta file"
keywords:
  - genome
  - gff3
  - annotation
  - validation
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`
  - gff3:
      type: file
      description: Input gff3 file
      pattern: "*.{gff,gff3}"
  - fasta:
      type: file
      description: Input fasta file
      pattern: "*.{fsa,fa,fasta}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`
  - success_log:
      type: file
      description: Log file for successful validation
      pattern: "*.success.log"
  - error_log:
      type: file
      description: Log file for failed validation
      pattern: "*.error.log"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@GallVp"
maintainers:
  - "@GallVp"
